### ISSUE TITLE
Add readme and about description

### ISSUE THREAD

**Issue by devRabbani** [canwebe/astrodata#4]
Give good description about the app
@MOHD-STREAM

**Comment by MOHD-STREAM** [comment]
Will be done tomorrow.

**Comment by devRabbani** [comment]
No promlem take your time.
And if you do anything then first insert issue and then try.
@MOHD-STREAM

**Comment by devRabbani** [comment]
@Mohd-Zahid-01 Zahid if you are not doing this then moved this to To-Do

**Comment by Mohd-Zahid-01** [comment]
In Progress will be completed in short time.

**Comment by devRabbani** [comment]
Comment what are you doing like doing it,finshed,will do tommorow etc @Mohd-Zahid-01

**Comment by Mohd-Zahid-01** [comment]
@devRabbani In Progress now.
